export const products = [
  {
    id: 1,
    name: "Gradient Graphic T-shirt",
    price: 145,
    currency: "$",
    image: "image 1.png",
    rating: 4,
    maxRating: 5,
    stock: 212,
    stockUnit: "pcs left",
    color: "Olive Green",
    category: "T-shirts",
    brand: "QOLFR", // Based on visible text on shirt
    size: ["S", "M", "L", "XL"], // Common t-shirt sizes
    description: "Stylish gradient graphic t-shirt with modern design",
    inCart: true, // Since "Remove from Cart" button is visible
    availability: "in_stock"
  },
  {
    id: 2,
    name: "Polo with Tipping Details",
    price: 180,
    currency: "$",
    image: "image 7.png",
    rating: 1,
    maxRating: 5,
    stock: 320,
    stockUnit: "pcs left",
    color: "Orange/Black",
    category: "Polo Shirts",
    brand: "Generic",
    size: ["S", "M", "L", "XL"],
    description: "Orange polo shirt with black tipping details and striped pattern",
    inCart: false, // Since "Add to Cart" button is visible
    availability: "in_stock"
  },
  {
    id: 3,
    name: "Black Striped T-shirt",
    price: 120,
    originalPrice: 160,
    currency: "$",
    image: "image 7-1.png",
    rating: 3,
    maxRating: 5,
    stock: 420,
    stockUnit: "pcs left",
    color: "Black",
    category: "T-shirts",
    brand: "Generic",
    size: ["S", "M", "L", "XL"],
    description: "Black t-shirt with vertical stripes pattern",
    inCart: false, // Since "Add to Cart" button is visible
    availability: "in_stock",
    onSale: true
  },
  {
    id: 4,
    name: "Skinny Fit Jeans",
    price: 240,
    originalPrice: 260,
    currency: "$",
    image: "image 8.png",
    rating: 4,
    maxRating: 5,
    stock: 20,
    stockUnit: "pcs left",
    color: "Teal Blue",
    category: "Jeans",
    brand: "Generic",
    size: ["28", "30", "32", "34", "36"], // Common jean sizes
    description: "Skinny fit jeans in teal blue color",
    inCart: false, // Since "Add to Cart" button is visible
    availability: "low_stock",
    onSale: true
  },
  {
    id: 5,
    name: "Checkered Shirt",
    price: 180,
    currency: "$",
    image: "image 8-1.png",
    rating: 4,
    maxRating: 5,
    stock: 20,
    stockUnit: "pcs left",
    color: "Orange",
    category: "Shirts",
    brand: "Generic",
    size: ["S", "M", "L", "XL"],
    description: "Orange checkered casual shirt with modern fit",
    inCart: false, // Since "Add to Cart" button is visible
    availability: "low_stock"
  },
  {
    id: 6,
    name: "Sleeve Striped T-shirt",
    price: 130,
    originalPrice: 160,
    currency: "$",
    image: "image 8-2.png",
    rating: 4,
    maxRating: 5,
    stock: 20,
    stockUnit: "pcs left",
    color: "White/Multi",
    category: "T-shirts",
    brand: "Generic",
    size: ["S", "M", "L", "XL"],
    description: "White t-shirt with colorful graphic design and striped sleeves",
    inCart: false, // Since "Add to Cart" button is visible
    availability: "low_stock",
    onSale: true
  },
  {
    id: 7,
    name: "Vertical Striped Shirt",
    price: 212,
    originalPrice: 232,
    currency: "$",
    image: "image 9.png",
    rating: 4,
    maxRating: 5,
    stock: 20,
    stockUnit: "pcs left",
    color: "Navy/Red/White",
    category: "Shirts",
    brand: "Generic",
    size: ["S", "M", "L", "XL"],
    description: "Vertical striped button-up shirt in navy, red and white",
    inCart: false, // Since "Add to Cart" button is visible
    availability: "low_stock",
    onSale: true
  },
  {
    id: 8,
    name: "Courage Graphic T-shirt",
    price: 145,
    currency: "$",
    image: "image 9-1.png",
    rating: 4,
    maxRating: 5,
    stock: 20,
    stockUnit: "pcs left",
    color: "Light Blue",
    category: "T-shirts",
    brand: "Generic",
    size: ["S", "M", "L", "XL"],
    description: "Light blue t-shirt with courage graphic design",
    inCart: false, // Since "Add to Cart" button is visible
    availability: "low_stock"
  },
  {
    id: 9,
    name: "Loose Fit Bermuda Shorts",
    price: 80,
    currency: "$",
    image: "image 9-2.png",
    rating: 4.5,
    maxRating: 5,
    stock: 10,
    stockUnit: "pcs left",
    color: "Dusty Pink",
    category: "Shorts",
    brand: "Generic",
    size: ["S", "M", "L", "XL"],
    description: "Loose fit bermuda shorts in dusty pink color",
    inCart: false, // Since "Add to Cart" button is visible
    availability: "very_low_stock"
  },
  {
    id: 10,
    name: "Casual Summer Dress",
    price: 95,
    currency: "$",
    image: "image 10.png",
    rating: 5,
    maxRating: 5,
    stock: 45,
    stockUnit: "pcs left",
    color: "Floral Print",
    category: "Dresses",
    brand: "Generic",
    size: ["XS", "S", "M", "L", "XL"],
    description: "Beautiful casual summer dress with floral pattern",
    inCart: false,
    availability: "in_stock"
  },
  {
    id: 11,
    name: "Sporty Active Wear",
    price: 75,
    currency: "$",
    image: "image 10-1.png",
    rating: 4,
    maxRating: 5,
    stock: 30,
    stockUnit: "pcs left",
    color: "Gray/Black",
    category: "Active Wear",
    brand: "Generic",
    size: ["S", "M", "L", "XL"],
    description: "Comfortable sporty active wear for workouts",
    inCart: false,
    availability: "in_stock"
  },
  {
    id: 12,
    name: "Elegant Evening Wear",
    price: 280,
    currency: "$",
    image: "image 10-2.png",
    rating: 5,
    maxRating: 5,
    stock: 15,
    stockUnit: "pcs left",
    color: "Black",
    category: "Evening Wear",
    brand: "Generic",
    size: ["S", "M", "L"],
    description: "Elegant black evening wear for special occasions",
    inCart: false,
    availability: "low_stock"
  }
];